["aroma"] = {
        [1] = {
            name = "aroma-muffin",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "aroma-donut",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "aroma-cake",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "aroma-scone",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "aroma-crossant",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 5,
        },
     
        
    },
    
    ["burger2"] = {
        [1] = {
            name = "burger-bleeder",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "burger-moneyshot",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "burger-torpedo",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "burger-heartstopper",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "burger-meatfree",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "burger-fries",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "burger-softdrink",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [8] = {
            name = "burger-mshake",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        
    },

    ["uwu"] = {
        [1] = {
            name = "uwububbleteablueberry",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "uwububbletearose",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "uwububbleteamint",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "uwupancake",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "uwucupcake",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "uwuvanillasandy",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "uwuchocsandy",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [8] = {
            name = "uwubudhabowl",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [9] = {
            name = "uwusushi",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        [10] = {
            name = "uwumisosoup",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
        },
        
    },